vim.keymap.set("n", "<leader>gd", vim.lsp.buf.definition, {})
vim.keymap.set("n", "<leader>gr", vim.lsp.buf.references, {})
-- vim.keymap.set("n", "<leader>rn", vim.lsp.buf.rename, {})
vim.keymap.set("n", "<leader>rn", ":IncRename ")
-- vim.keymap.set("n", "<leader>rn", function()
-- 	return ":IncRename " .. vim.fn.expand("<cword>")
-- end, { expr = true })
